import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
import datetime

# Path to the CSV file generated by the Java program



def read_and_plot(i):
    try:
        # Read the CSV file
        data = pd.read_csv('metrics_data.csv', names=['Time', 'CPU Usage', 'Memory Usage', 'Disk Usage (Free)', 'Disk Usage (Total)'])
        data = data.tail(1200)
        data['Time'] = pd.to_datetime(data['Time'])

        # Clear the current figure
        plt.clf()

        # Plot CPU Usage
        plt.subplot(3, 1, 1)
        plt.plot(data['Time'], data['CPU Usage'], label='CPU Usage (%)')
        plt.xlabel('Time')
        plt.ylabel('CPU Usage (%)')
        plt.xticks(rotation=45)
        plt.legend()

        # Plot Memory Usage
        plt.subplot(3, 1, 2)
        plt.plot(data['Time'], data['Memory Usage'], label='Memory Usage (Bytes)')
        plt.xlabel('Time')
        plt.ylabel('Memory Usage (Bytes)')
        plt.xticks(rotation=45)
        plt.legend()

        # Plot Disk Usage
        plt.subplot(3, 1, 3)
        plt.plot(data['Time'], data['Disk Usage (Free)'], label='Disk Free (Bytes)')
        plt.plot(data['Time'], data['Disk Usage (Total)'], label='Disk Total (Bytes)')
        plt.xlabel('Time')
        plt.ylabel('Disk Usage (Bytes)')
        plt.xticks(rotation=45)
        plt.legend()

        # Layout adjustment
        plt.tight_layout()
    except Exception as e:
        print(f"Error reading the CSV file: {e}")

# Set up the plot
plt.figure(figsize=(10, 8))

# Create an animation that updates the plot every second
ani = FuncAnimation(plt.gcf(), read_and_plot, interval=1000)

# Show the plot
plt.show()
